# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: {{ .Values.app-name }}
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: {{ .Values.app-name }}
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: {{ .Values.app-name }}
    spec:
      containers:
        # The container name to execute pods
        - name: {{ .Values.app-name }}
          # pull postgresimage from docker hub
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: {{ .Values.app-name }}-secret-credentials
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgres/data
              name: {{ .Values.app-name }}-data
      # Volumes attached to the pod
      volumes:
        - name: {{ .Values.app-name }}-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: {{ .Values.app-name }}-persistent-volume-claim            