{{- if .Values.webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appname }}-web
    labels:
        app: {{ .Values.appname }}-web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.appname }}-web
    template:
        metadata:
            labels:
                app: {{ .Values.appname }}-web
                version: v1
        spec:
            containers: 
            -   name: {{ .Values.appname }}-web
                image: sha256:dcf036ba76d58eb604ce0e78af468ff916ee86206dae30bb411514d760c4008f
                ports:
                -   containerPort: 8080
                    protocol: TCP
                env:
                -   name: "ASPNETCORE_ENVIRONMENT"
                    value: "Development"
                -   name: "ASPNETCORE_URLS"
                    value: http://+:8080
                -   name: ConnectionStrings__DBConnectionString
                    value: "Server={{ .Values.app-name }};Database=testDB;Username=testUser;Password=testPassword1"    
                resources:
                    limits:
                        memory: "128Mi"
                        cpu: "100m"
{{- end -}}                       