{{- if .Values.webapp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}-web
  ports:
    - name: "80"
      port: {{ .Values.webport }}
      targetPort: 8080
      # nodePort: 8080
{{- end -}}         