apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: "80"
      port: 32150
      targetPort: 8080
      # nodePort: 8080